name: Deploy Nginx Configuration

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "REGION_CODE=${{ secrets.REGION_CODE }}" >> $GITHUB_ENV

      - name: Replace placeholders in Nginx config
        run: |
          sed -i "s/{{ BUCKET_NAME }}/${{ secrets.BUCKET_NAME }}/g" /path/to/ne.conf
          sed -i "s/{{ REGION_CODE }}/${{ secrets.REGION_CODE }}/g" /path/to/ne.conf

      - name: Deploy Nginx Configuration
        run: |
          # Reload Nginx or copy the configuration to the appropriate directory
          sudo nginx -t  # Test the configuration
          sudo systemctl reload nginx  # Reload Nginx